<a href="https://colab.research.google.com/github/Priya-Kumari-Chourasia/deep_learning/blob/main/using_pretrained_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow


In [3]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions

import numpy as np

In [4]:
model = ResNet50(weights='imagenet')

102967424/102967424 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [12]:
img_path = '/content/eleph.png'
img=image.load_img(img_path,target_size=(224,224))
x = image.img_to_array(img)
x

array([[[178., 172., 153.],
        [139., 144., 103.],
        [149., 152.,  95.],
        ...,
        [180., 193., 151.],
        [198., 215., 182.],
        [217., 231., 222.]],

       [[197., 191., 159.],
        [233., 235., 212.],
        [210., 208., 170.],
        ...,
        [208., 218., 183.],
        [167., 172., 136.],
        [233., 246., 250.]],

       [[229., 219., 189.],
        [153., 148., 115.],
        [230., 225., 195.],
        ...,
        [238., 249., 245.],
        [115., 122.,  90.],
        [166., 174., 170.]],

       ...,

       [[205., 184., 117.],
        [209., 187., 117.],
        [206., 195., 122.],
        ...,
        [212., 211., 188.],
        [115., 114.,  61.],
        [237., 235., 183.]],

       [[221., 208., 148.],
        [183., 181., 103.],
        [205., 197., 135.],
        ...,
        [ 92.,  90.,  45.],
        [185., 176., 143.],
        [142., 130.,  75.]],

       [[233., 218., 165.],
        [167., 172.,  88.],
        [204., 1

In [13]:
x = np.expand_dims(x,axis=0)
x

array([[[[178., 172., 153.],
         [139., 144., 103.],
         [149., 152.,  95.],
         ...,
         [180., 193., 151.],
         [198., 215., 182.],
         [217., 231., 222.]],

        [[197., 191., 159.],
         [233., 235., 212.],
         [210., 208., 170.],
         ...,
         [208., 218., 183.],
         [167., 172., 136.],
         [233., 246., 250.]],

        [[229., 219., 189.],
         [153., 148., 115.],
         [230., 225., 195.],
         ...,
         [238., 249., 245.],
         [115., 122.,  90.],
         [166., 174., 170.]],

        ...,

        [[205., 184., 117.],
         [209., 187., 117.],
         [206., 195., 122.],
         ...,
         [212., 211., 188.],
         [115., 114.,  61.],
         [237., 235., 183.]],

        [[221., 208., 148.],
         [183., 181., 103.],
         [205., 197., 135.],
         ...,
         [ 92.,  90.,  45.],
         [185., 176., 143.],
         [142., 130.,  75.]],

        [[233., 218., 165.],
       

In [14]:
x = preprocess_input(x)
x

array([[[[ 49.060997 ,  55.221    ,  54.32     ],
         [ -0.939003 ,  27.221    ,  15.32     ],
         [ -8.939003 ,  35.221    ,  25.32     ],
         ...,
         [ 47.060997 ,  76.221    ,  56.32     ],
         [ 78.061    ,  98.221    ,  74.32     ],
         [118.061    , 114.221    ,  93.32     ]],

        [[ 55.060997 ,  74.221    ,  73.32     ],
         [108.061    , 118.221    , 109.32     ],
         [ 66.061    ,  91.221    ,  86.32     ],
         ...,
         [ 79.061    , 101.221    ,  84.32     ],
         [ 32.060997 ,  55.221    ,  43.32     ],
         [146.061    , 129.22101  , 109.32     ]],

        [[ 85.061    , 102.221    , 105.32     ],
         [ 11.060997 ,  31.221    ,  29.32     ],
         [ 91.061    , 108.221    , 106.32     ],
         ...,
         [141.061    , 132.22101  , 114.32     ],
         [-13.939003 ,   5.2210007,  -8.68     ],
         [ 66.061    ,  57.221    ,  42.32     ]],

        ...,

        [[ 13.060997 ,  67.221    ,  8

In [15]:
preds= model.predict(x)
print('Predicted: ',decode_predictions(preds,top=3)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
35363/35363 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Predicted:  [('n02504458', 'African_elephant', np.float32(0.88127637)), ('n01871265', 'tusker', np.float32(0.11544891)), ('n02504013', 'Indian_elephant', np.float32(0.0032747462))]
